name: Build Flutter App

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install Dependencies
        run: flutter pub get

      - name: Create Constants File
        run: |
          echo "class AppConstants {" > lib/core/constants.dart
          echo "  static const String appName = 'Media Pad';" >> lib/core/constants.dart
          echo "  static const String appTitle = 'Title';" >> lib/core/constants.dart
          echo "  static const String tokenKey = '${{ secrets.TOKEN_KEY }}';" >> lib/core/constants.dart
          echo "  static const String userKey = '${{ secrets.USER_KEY }}';" >> lib/core/constants.dart
          echo "  static const String baseUrl = '${{ secrets.BASE_URL }}';" >> lib/core/constants.dart
          echo "}" >> lib/core/constants.dart

      - name: Build APK
        run: flutter build apk --release

      - name: Get Version Name
        run: echo "VERSION_NAME=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Upload APK to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          APK_PATH=build/app/outputs/flutter-apk/app-release.apk
          TAG_NAME="v${{ env.VERSION_NAME }}"
          RELEASE_NAME="Release ${{ env.VERSION_NAME }}"
          gh release create "$TAG_NAME" "$APK_PATH" --title "$RELEASE_NAME" --notes "New release of MediaPad."